export const CHANNEL = 'FORK_IPC_CHANNEL'

export enum ACTIONS {
  ASK_REGISTER = 'ASK_REGISTER',
  EMIT = 'EMIT',
  EXECUTE = 'EXECUTE',
  PROXY_EXECUTE = 'PROXY_EXECUTE',
  REGISTER = 'REGISTER',
  RESULT = 'RESULT',
  PROXY_RESULT = 'PROXY_RESULT',
}

export enum STATUS {
  FAIL = 'FAIL',
  OK = 'OK',
  PENDING = 'PENDING',
}
